main: me.bixgamer707.killsrewards.KillsRewards
version: 1.1.3
author: bixgamer707
api-version: 1.13
name: KillsRewards
softdepend: [Vault]

commands:
  killsrewards:
    description: KillsRewards's main command.
    aliases: [kr]
  bounty:
    description: Become a bounty hunter! 